server:
  port: 8080

spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  application:
    name: lumi
  # active 프로필 설정은 한 번만 명시합니다.
  profiles:
    active: local

  # 이미지 파일 용량 제한
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MariaDBDialect
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 30000
  refresh-expiration: 604800000

---
# local 프로필 설정
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: 6379
      password: ${LOCAL_REDIS_PASSWORD}


---
# dev 프로필 설정
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379
      password: ${DEV_REDIS_PASSWORD}

logging:
  level:
    org.springframework: INFO
